In [1]:
import numpy as np
import networkx as nx

# Part 1.a

#### Matrix M of Graph 1.a

In [2]:
# A, B, C, D, E
M = np.array ([[0, 1, 1, 1, 1], 
        [1, 0, 1, 1, 1],
        [1, 1, 0, 1, 1],
        [1, 1, 1, 0, 1],
        [0, 0, 0, 0, 0]])
M

array([[0, 1, 1, 1, 1],
       [1, 0, 1, 1, 1],
       [1, 1, 0, 1, 1],
       [1, 1, 1, 0, 1],
       [0, 0, 0, 0, 0]])

####  M.T

In [3]:
M_T = M.T
M_T

array([[0, 1, 1, 1, 0],
       [1, 0, 1, 1, 0],
       [1, 1, 0, 1, 0],
       [1, 1, 1, 0, 0],
       [1, 1, 1, 1, 0]])

####  M * M.T

In [4]:
MM_T = np.matmul(M, M_T)
MM_T

array([[4, 3, 3, 3, 0],
       [3, 4, 3, 3, 0],
       [3, 3, 4, 3, 0],
       [3, 3, 3, 4, 0],
       [0, 0, 0, 0, 0]])

####  M.T * M

In [5]:
M_TM = np.matmul(M_T, M)
M_TM

array([[3, 2, 2, 2, 3],
       [2, 3, 2, 2, 3],
       [2, 2, 3, 2, 3],
       [2, 2, 2, 3, 3],
       [3, 3, 3, 3, 4]])

#### h (round 1)

In [6]:
h_1 = np.array([[1, 1, 1, 1, 1]]).T
h_1

array([[1],
       [1],
       [1],
       [1],
       [1]])

#### a (round 1)

In [7]:
a_1 = np.array([[1, 1, 1, 1, 1]]).T
a_1

array([[1],
       [1],
       [1],
       [1],
       [1]])

#### h (round 2)

In [8]:
h_2 = np.matmul(MM_T, h_1)
h_2 = h_2/max(h_2)
h_2

array([[1.],
       [1.],
       [1.],
       [1.],
       [0.]])

#### a (round 2)

In [9]:
a_2 = np.matmul(M_TM, a_1)
a_2 = a_2/max(a_2)
a_2

array([[0.75],
       [0.75],
       [0.75],
       [0.75],
       [1.  ]])

#### h (round 3)

In [10]:
h_3 = np.matmul(MM_T, h_2)
h_3 = h_3/max(h_3)
h_3

array([[1.],
       [1.],
       [1.],
       [1.],
       [0.]])

#### a (round 3)

In [11]:
a_3 = np.matmul(M_TM, a_2)
a_3 = a_3/max(a_3)
a_3

array([[0.75],
       [0.75],
       [0.75],
       [0.75],
       [1.  ]])

## result 
- h (round 3) == h (round 2) 
- a (round 3) == a (round 2)  

# Part 1.b

#### normlized M

In [12]:
# A, B, C, D, E
M = np.array ([[0, 1, 1, 1, 1], 
        [1, 0, 1, 1, 1],
        [1, 1, 0, 1, 1],
        [1, 1, 1, 0, 1],
        [0, 0, 0, 0, 0]]).T

# normlize M
sums = M.sum(axis=0, keepdims=1)
sums[sums==0] = 1

M = M / sums
M

array([[0.  , 0.25, 0.25, 0.25, 0.  ],
       [0.25, 0.  , 0.25, 0.25, 0.  ],
       [0.25, 0.25, 0.  , 0.25, 0.  ],
       [0.25, 0.25, 0.25, 0.  , 0.  ],
       [0.25, 0.25, 0.25, 0.25, 0.  ]])

#### v

In [13]:
v1 = (np.array([[1, 1, 1, 1, 1]])/5).T
v1

array([[0.2],
       [0.2],
       [0.2],
       [0.2],
       [0.2]])

#### Page Rank v = M * v 
- Node E is deadend so we should revise this frormula with a tax 
- for 20% tax we have:  v = (1-0.2) M * v + 0.2 * e -> v = 0.8 M * v + 0.2 * 0.2


#### v (round 2)

In [14]:
v2 = 0.8 * np.matmul(M, v1) + 0.04
v2

array([[0.16],
       [0.16],
       [0.16],
       [0.16],
       [0.2 ]])

#### v (round 3)

In [15]:
v3 = 0.8 * np.matmul(M, v2) + 0.04
v3

array([[0.136],
       [0.136],
       [0.136],
       [0.136],
       [0.168]])

#### Pagerank (after 52 round)

In [16]:
threshold=1e-12
max_iter = 1000
count = 3
v = v3
v_before = v2
while np.linalg.norm(v - v_before) >= threshold:
        if (count> max_iter):
            break
        v_before = v
        v = 0.8 * np.matmul(M, v_before) + 0.04
        count +=1
        print(f"round v{count}:\n {v} \n")

round v4:
 [[0.1216]
 [0.1216]
 [0.1216]
 [0.1216]
 [0.1488]] 

round v5:
 [[0.11296]
 [0.11296]
 [0.11296]
 [0.11296]
 [0.13728]] 

round v6:
 [[0.107776]
 [0.107776]
 [0.107776]
 [0.107776]
 [0.130368]] 

round v7:
 [[0.1046656]
 [0.1046656]
 [0.1046656]
 [0.1046656]
 [0.1262208]] 

round v8:
 [[0.10279936]
 [0.10279936]
 [0.10279936]
 [0.10279936]
 [0.12373248]] 

round v9:
 [[0.10167962]
 [0.10167962]
 [0.10167962]
 [0.10167962]
 [0.12223949]] 

round v10:
 [[0.10100777]
 [0.10100777]
 [0.10100777]
 [0.10100777]
 [0.12134369]] 

round v11:
 [[0.10060466]
 [0.10060466]
 [0.10060466]
 [0.10060466]
 [0.12080622]] 

round v12:
 [[0.1003628 ]
 [0.1003628 ]
 [0.1003628 ]
 [0.1003628 ]
 [0.12048373]] 

round v13:
 [[0.10021768]
 [0.10021768]
 [0.10021768]
 [0.10021768]
 [0.12029024]] 

round v14:
 [[0.10013061]
 [0.10013061]
 [0.10013061]
 [0.10013061]
 [0.12017414]] 

round v15:
 [[0.10007836]
 [0.10007836]
 [0.10007836]
 [0.10007836]
 [0.12010449]] 

round v16:
 [[0.10004702]
 [0.100047

#### Pagerank

In [17]:
# normlize
v_pagerank = v/sum(v)
v_pagerank

array([[0.19230769],
       [0.19230769],
       [0.19230769],
       [0.19230769],
       [0.23076923]])

#### Trustrank (after 53 round)

In [18]:
threshold = 1e-12
max_iter = 1000
count = 1
v = (np.array([[1, 1, 1, 1, 1]])/5).T
v_before = np.array([[0, 0, 0, 0, 0]]).T

while np.linalg.norm(v - v_before) >= threshold:
        if (count> max_iter):
            break
        v_before = v
        # D
        v = 0.8 * np.matmul(M, v_before) + np.array([[0, 0, 0, 0.04, 0]]).T
        count +=1
        print(f"round v{count}:\n {v} \n")

round v2:
 [[0.12]
 [0.12]
 [0.12]
 [0.16]
 [0.16]] 

round v3:
 [[0.08 ]
 [0.08 ]
 [0.08 ]
 [0.112]
 [0.104]] 

round v4:
 [[0.0544]
 [0.0544]
 [0.0544]
 [0.088 ]
 [0.0704]] 

round v5:
 [[0.03936]
 [0.03936]
 [0.03936]
 [0.07264]
 [0.05024]] 

round v6:
 [[0.030272]
 [0.030272]
 [0.030272]
 [0.063616]
 [0.038144]] 

round v7:
 [[0.024832 ]
 [0.024832 ]
 [0.024832 ]
 [0.0581632]
 [0.0308864]] 

round v8:
 [[0.02156544]
 [0.02156544]
 [0.02156544]
 [0.0548992 ]
 [0.02653184]] 

round v9:
 [[0.01960602]
 [0.01960602]
 [0.01960602]
 [0.05293926]
 [0.0239191 ]] 

round v10:
 [[0.01843026]
 [0.01843026]
 [0.01843026]
 [0.05176361]
 [0.02235146]] 

round v11:
 [[0.01772483]
 [0.01772483]
 [0.01772483]
 [0.05105816]
 [0.02141088]] 

round v12:
 [[0.01730156]
 [0.01730156]
 [0.01730156]
 [0.0506349 ]
 [0.02084653]] 

round v13:
 [[0.0170476 ]
 [0.0170476 ]
 [0.0170476 ]
 [0.05038094]
 [0.02050792]] 

round v14:
 [[0.01689523]
 [0.01689523]
 [0.01689523]
 [0.05022856]
 [0.02030475]] 

round v1

#### Trustrank

In [19]:
# normlize
v_trustrank = v/sum(v)
v_trustrank

array([[0.13888889],
       [0.13888889],
       [0.13888889],
       [0.41666667],
       [0.16666667]])

#### Spam Mass (vp-vt)/vp

In [20]:
spam_mass = (v_pagerank - v_trustrank) / v_pagerank
spam_mass

array([[ 0.27777778],
       [ 0.27777778],
       [ 0.27777778],
       [-1.16666667],
       [ 0.27777778]])

# Part 2

In [21]:
d = 3
G = nx.balanced_tree(2, d, create_using=nx.DiGraph())
# add loop
G.add_edge(0,0)
M = nx.convert_matrix.to_numpy_array(G)

In [22]:
M_T = M.T
MM_T = np.matmul(M, M_T)
M_TM = np.matmul(M_T, M)


In [23]:
h_1 = np.array([1]*(2 **(d+1)-1)).T
a_1 = np.array([1]*(2 **(d+1)-1)).T


#### h (round 2)

In [24]:
h_2 = np.matmul(MM_T, h_1)
h_2 = h_2/max(h_2)
h_2

array([1.        , 0.66666667, 0.66666667, 0.66666667, 0.66666667,
       0.66666667, 0.66666667, 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ])

#### a (round 2)

In [25]:
a_2 = np.matmul(M_TM, a_1)
a_2 = a_2/max(a_2)
a_2

array([1.        , 1.        , 1.        , 0.66666667, 0.66666667,
       0.66666667, 0.66666667, 0.66666667, 0.66666667, 0.66666667,
       0.66666667, 0.66666667, 0.66666667, 0.66666667, 0.66666667])

#### h (round 3)

In [26]:
h_3 = np.matmul(MM_T, h_2)
h_3 = h_3/max(h_3)
h_3

array([1.        , 0.44444444, 0.44444444, 0.44444444, 0.44444444,
       0.44444444, 0.44444444, 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ])

#### a (round 3)

In [27]:
a_3 = np.matmul(M_TM, a_2)
a_3 = a_3/max(a_3)
a_3

array([1.        , 1.        , 1.        , 0.44444444, 0.44444444,
       0.44444444, 0.44444444, 0.44444444, 0.44444444, 0.44444444,
       0.44444444, 0.44444444, 0.44444444, 0.44444444, 0.44444444])

#### h (round 4)

In [28]:
h_4 = np.matmul(MM_T, h_3)
h_4 = h_4/max(h_4)
h_4

array([1.       , 0.2962963, 0.2962963, 0.2962963, 0.2962963, 0.2962963,
       0.2962963, 0.       , 0.       , 0.       , 0.       , 0.       ,
       0.       , 0.       , 0.       ])

#### a (round 4)

In [29]:
a_4 = np.matmul(M_TM, a_3)
a_4 = a_4/max(a_4)
a_4

array([1.       , 1.       , 1.       , 0.2962963, 0.2962963, 0.2962963,
       0.2962963, 0.2962963, 0.2962963, 0.2962963, 0.2962963, 0.2962963,
       0.2962963, 0.2962963, 0.2962963])

#### ...

In [30]:
h_i = h_4
a_i = a_3
for i in range(5, 100):
    h_i = np.matmul(MM_T, h_i)
    h_i = h_i/max(h_i)
    a_i = np.matmul(M_TM, a_i)
    a_i = a_i/max(a_i)

#### h (round 99)

In [31]:
h_i

array([1.00000000e+00, 5.53422246e-18, 5.53422246e-18, 5.53422246e-18,
       5.53422246e-18, 5.53422246e-18, 5.53422246e-18, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00])

#### a (round 99)

In [32]:
a_i

array([1.00000000e+00, 1.00000000e+00, 1.00000000e+00, 8.30133369e-18,
       8.30133369e-18, 8.30133369e-18, 8.30133369e-18, 8.30133369e-18,
       8.30133369e-18, 8.30133369e-18, 8.30133369e-18, 8.30133369e-18,
       8.30133369e-18, 8.30133369e-18, 8.30133369e-18])

## result 
- h = [1, 0, 0, ..., 0].T
- a = [1, 1, 1, 0, 0, ..., 0].T