In [1]:
# All details in Pdf 

In [5]:
import numpy as np
W = np.array([[1, 0, 0],
              [1, 0, 0],
              [0, 1, 1]])

X, Z, Y_T = np.linalg.svd(W)
Z_pinv = np.linalg.pinv(np.diag(Z))
U = Y_T.T @ Z_pinv ** 2 @ X.T
U

array([[0.35355339, 0.35355339, 0.        ],
       [0.        , 0.        , 0.35355339],
       [0.        , 0.        , 0.35355339]])

In [23]:
C = np.array([[np.sqrt(3), 0, 0],
             [0, 0, 1],
             [0, np.sqrt(3/2), 1],
             [0, np.sqrt(3/2), 1]])
C

array([[1.73205081, 0.        , 0.        ],
       [0.        , 0.        , 1.        ],
       [0.        , 1.22474487, 1.        ],
       [0.        , 1.22474487, 1.        ]])

In [25]:
R = np.array ([[np.sqrt(3/2), 1, 0, 0, 0],
               [np.sqrt(3/2),np.sqrt(3/2), 0,0,0],
               [0,0,np.sqrt(3/2),0,np.sqrt(3/2)]])
R

array([[1.22474487, 1.        , 0.        , 0.        , 0.        ],
       [1.22474487, 1.22474487, 0.        , 0.        , 0.        ],
       [0.        , 0.        , 1.22474487, 0.        , 1.22474487]])

In [26]:
C @ U @ R

array([[1.5       , 1.36237244, 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.4330127 , 0.        , 0.4330127 ],
       [0.        , 0.        , 0.96334279, 0.        , 0.96334279],
       [0.        , 0.        , 0.96334279, 0.        , 0.96334279]])